org: kool4caats
service: prind-api
app: prind

plugins:
  - serverless-python-requirements
  - serverless-pseudo-parameters
  - serverless-aws-documentation
  - serverless-openapi-documentation
  - serverless-reqvalidator-plugin
  - check-git-branch-before-deploy
  - serverless-plugin-aws-alerts


custom:
  checkGitBranchBeforeDeploy:
      dev: dev
      staging: staging
      production: master
  pythonRequirements:
    dockerizePip: true
  myEnvironment:
    # map Factom network based on stage
    FOUNDATIONS_API_ID:
      dev: 'w9t59cws74'
      staging: ''
      production: ''
    SP_DID:
      dev: 'did:fctr:d85be1f5baa83fa83850d8b58731a7f7c8ba65c33dec107c2e16e0dd65c7bcc7'
      staging: ''
      production: ''
  s3BucketName: prind-portal-user-files-${self:provider.stage}
 
  documentation:
    api:
      info:
        version: v0.0.1 
        title: Prind API
    models:
      - name: emptyResponse
        description: The response given when there is no data to return
        contentType: "application/json"
        schema: ${file(models/emptyResponse.json)}
      - name: errorResponse
        description:
        contentType: "application/json"
        schema: ${file(models/errorResponse.json)}
      - name: rolesGetResponse
        description:
        contentType: "application/json"
        schema: ${file(models/rolesGetResponse.json)}

provider:
  name: aws
  runtime: python3.7
  region: ${opt:region, 'eu-west-1'}
  stage: ${opt:stage, 'dev'}
  environment:
    TABLE_NAME: ${self:app}-${self:provider.stage}
    FOUNDATIONS_API_STAGE: ${self:provider.stage}
    FOUNDATIONS_API_ID: ${self:custom.myEnvironment.FOUNDATIONS_API_ID.${self:provider.stage}}
    SP_DID: ${self:custom.myEnvironment.SP_DID.${self:provider.stage}}
    S3_BUCKET_NAME: ${self:custom.s3BucketName} 
    S3_BUCKET_ARN: "arn:aws:s3:::${self:custom.s3BucketName}"    

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - 'sts:AssumeRole'
      Resource: arn:aws:iam::#{AWS::AccountId}:role/webClientRole

      # Permissions for the main table
    - Effect: "Allow"
      Action:
        - 'dynamodb:PutItem'
        - 'dynamodb:GetItem'
        - 'dynamodb:UpdateItem'
        - 'dynamodb:DeleteItem'
        - 'dynamodb:Query'
      Resource: arn:aws:dynamodb:#{AWS::Region}:#{AWS::AccountId}:table/${self:provider.environment.TABLE_NAME}
      # Permissions for the GSI1 index
    - Effect: "Allow"
      Action:
        - 'dynamodb:PutItem'
        - 'dynamodb:GetItem'
        - 'dynamodb:UpdateItem'
        - 'dynamodb:DeleteItem'
        - 'dynamodb:Query'
      Resource: arn:aws:dynamodb:#{AWS::Region}:#{AWS::AccountId}:table/${self:provider.environment.TABLE_NAME}/index/GSI1
    # Allow operations on S3 bucket
    - Effect: "Allow"
      Action:
        - "s3:GetObject"
        - "s3:PutObject"
      Resource: "${self:provider.environment.S3_BUCKET_ARN}/*"


package:
  exclude:
    - node_modules/**
    - venv/**
    - __pycache__/**



functions:
  get-sts:
    handler: get-sts.lambda_handler
    events:
      - http:
          path: /user/get-sts
          method: get
          cors: true
          response:
            statusCodes:
              200:
                pattern: '' # Default response method
              400:
                pattern: '.*"statusCode":400,.*'
              500:
                pattern: '.*"statusCode":500,.*'
          integration: lambda
          # documentation:
          #   methodResponses:
          #     - statusCode: "200"
          #       responseBody:
          #         description: "Successful Response"
          #       responseModels:
          #         application/json: "userDetailsGetResponse"
          #     - statusCode: "400"
          #       responseBody:
          #         description: "A client error occurred"
          #       responseModels:
          #         application/json: "errorResponse"
          #     - statusCode: "500"
          #       responseBody:
          #         description: "A server error occurred"
          #       responseModels:
          #         application/json: "errorResponse"
          authorizer: 
            type: COGNITO_USER_POOLS
            authorizerId: 
              Ref: ApiGatewayAuthorizer

  get-roles:
    handler: get-roles.lambda_handler
    events:
      - http:
          path: /roles/get-roles
          method: get
          cors: true
          response:
            statusCodes:
              200:
                pattern: '' # Default response method
              400:
                pattern: '.*"statusCode":400,.*'
              500:
                pattern: '.*"statusCode":500,.*'
          integration: lambda
          documentation:
            methodResponses:
              - statusCode: "200"
                responseBody:
                  description: "Successful Response"
                responseModels:
                  application/json: "rolesGetResponse"
              - statusCode: "400"
                responseBody:
                  description: "A client error occurred"
                responseModels:
                  application/json: "errorResponse"
              - statusCode: "500"
                responseBody:
                  description: "A server error occurred"
                responseModels:
                  application/json: "errorResponse"
          authorizer: 
            type: COGNITO_USER_POOLS
            authorizerId: 
              Ref: ApiGatewayAuthorizer

  create-document:
    handler: create-document.lambda_handler
    # events:
    #   - s3:
    #       bucket: ${self:custom.s3BucketName}
    #       event: s3:ObjectCreated:*
    #       # existing: true
    #       versioning: true

  get-document:
    handler: get-document-versions.lambda_handler
    events:
      - http:
          path: /document/{document_did}
          method: get
          cors: true
          response:
            statusCodes:
              200:
                pattern: '' # Default response method
              400:
                pattern: '.*"statusCode":400,.*'
              500:
                pattern: '.*"statusCode":500,.*'
          integration: lambda
          documentation:
            methodResponses:
              - statusCode: "200"
                responseBody:
                  description: "Successful Response"
              - statusCode: "400"
                responseBody:
                  description: "A client error occurred"
                responseModels:
                  application/json: "errorResponse"
              - statusCode: "500"
                responseBody:
                  description: "A server error occurred"
                responseModels:
                  application/json: "errorResponse"
          authorizer: 
            type: COGNITO_USER_POOLS
            authorizerId: 
              Ref: ApiGatewayAuthorizer

  get-document-version-signatures:
    handler: get-document-version-signatures.lambda_handler
    events:
      - http:
          path: /document/{document_did}/version-signatures/{document_version}
          method: get
          cors: true
          response:
            statusCodes:
              200:
                pattern: '' # Default response method
              400:
                pattern: '.*"statusCode":400,.*'
              500:
                pattern: '.*"statusCode":500,.*'
          integration: lambda
          documentation:
            methodResponses:
              - statusCode: "200"
                responseBody:
                  description: "Successful Response"
              - statusCode: "400"
                responseBody:
                  description: "A client error occurred"
                responseModels:
                  application/json: "errorResponse"
              - statusCode: "500"
                responseBody:
                  description: "A server error occurred"
                responseModels:
                  application/json: "errorResponse"
          authorizer: 
            type: COGNITO_USER_POOLS
            authorizerId: 
              Ref: ApiGatewayAuthorizer

  list-projects:
    handler: list-projects.lambda_handler
    events:
      - http:
          path: /project/list
          method: get
          cors: true
          response:
            statusCodes:
              200:
                pattern: '' # Default response method
              400:
                pattern: '.*"statusCode":400,.*'
              500:
                pattern: '.*"statusCode":500,.*'
          integration: lambda
          documentation:
            methodResponses:
              - statusCode: "200"
                responseBody:
                  description: "Successful Response"
              - statusCode: "400"
                responseBody:
                  description: "A client error occurred"
                responseModels:
                  application/json: "errorResponse"
              - statusCode: "500"
                responseBody:
                  description: "A server error occurred"
                responseModels:
                  application/json: "errorResponse"
          authorizer: 
            type: COGNITO_USER_POOLS
            authorizerId: 
              Ref: ApiGatewayAuthorizer

  get-project:
    handler: get-project.lambda_handler
    events:
      - http:
          path: /project/{project_id}
          method: get
          cors: true
          response:
            statusCodes:
              200:
                pattern: '' # Default response method
              400:
                pattern: '.*"statusCode":400,.*'
              500:
                pattern: '.*"statusCode":500,.*'
          integration: lambda
          documentation:
            methodResponses:
              - statusCode: "200"
                responseBody:
                  description: "Successful Response"
              - statusCode: "400"
                responseBody:
                  description: "A client error occurred"
                responseModels:
                  application/json: "errorResponse"
              - statusCode: "500"
                responseBody:
                  description: "A server error occurred"
                responseModels:
                  application/json: "errorResponse"
          authorizer: 
            type: COGNITO_USER_POOLS
            authorizerId: 
              Ref: ApiGatewayAuthorizer

  create-project:
    handler: create-project.lambda_handler
    events:
      - http:
          path: /project/create
          method: post
          cors: true
          response:
            statusCodes:
              200:
                pattern: '' # Default response method
              400:
                pattern: '.*"statusCode":400,.*'
              500:
                pattern: '.*"statusCode":500,.*'
          integration: lambda
          documentation:
            methodResponses:
              - statusCode: "200"
                responseBody:
                  description: "Successful Response"
              - statusCode: "400"
                responseBody:
                  description: "A client error occurred"
                responseModels:
                  application/json: "errorResponse"
              - statusCode: "500"
                responseBody:
                  description: "A server error occurred"
                responseModels:
                  application/json: "errorResponse"
          authorizer: 
            type: COGNITO_USER_POOLS
            authorizerId: 
              Ref: ApiGatewayAuthorizer

  update-project:
    handler: update-project.lambda_handler
    events:
      - http:
          path: /project/{project_id}/update
          method: post
          cors: true
          response:
            statusCodes:
              200:
                pattern: '' # Default response method
              400:
                pattern: '.*"statusCode":400,.*'
              500:
                pattern: '.*"statusCode":500,.*'
          integration: lambda
          documentation:
            methodResponses:
              - statusCode: "200"
                responseBody:
                  description: "Successful Response"
              - statusCode: "400"
                responseBody:
                  description: "A client error occurred"
                responseModels:
                  application/json: "errorResponse"
              - statusCode: "500"
                responseBody:
                  description: "A server error occurred"
                responseModels:
                  application/json: "errorResponse"
          authorizer: 
            type: COGNITO_USER_POOLS
            authorizerId: 
              Ref: ApiGatewayAuthorizer

  add-project-role:
    handler: add-project-role.lambda_handler
    events:
      - http:
          path: /project/{project_id}/add-role
          method: post
          cors: true
          response:
            statusCodes:
              200:
                pattern: '' # Default response method
              400:
                pattern: '.*"statusCode":400,.*'
              500:
                pattern: '.*"statusCode":500,.*'
          integration: lambda
          documentation:
            methodResponses:
              - statusCode: "200"
                responseBody:
                  description: "Successful Response"
              - statusCode: "400"
                responseBody:
                  description: "A client error occurred"
                responseModels:
                  application/json: "errorResponse"
              - statusCode: "500"
                responseBody:
                  description: "A server error occurred"
                responseModels:
                  application/json: "errorResponse"
          authorizer: 
            type: COGNITO_USER_POOLS
            authorizerId: 
              Ref: ApiGatewayAuthorizer


resources:

  # DynamoDB Table
  - ${file(resources/dynamodb-table.yml)}

  # Cognito
  - ${file(resources/cognito-user-pool.yml)}

  # Cognito Authorizer
  - ${file(resources/cognito-authorizer.yml)}

  # RequestValidator
  - ${file(resources/request-validator.yml)}

    # S3 Bucket
  - ${file(resources/s3-bucket.yml)}
