Resources:
  ApiGatewayAuthorizer: 
    Type: AWS::ApiGateway::Authorizer
    Properties: 
      Name: foundations-user-pool-${self:provider.stage}
      Type: COGNITO_USER_POOLS
      IdentitySource: method.request.header.Authorization
      RestApiId: 
        Ref: ApiGatewayRestApi
      ProviderARNs: 
        - Fn::GetAtt:
          - CognitoUserPool
          - Arn