Resources:
  UserFilesS3Bucket:
    Type: AWS::S3::Bucket
    Properties: 
      AccessControl: Private
      BucketName: prind-portal-user-files-${self:provider.stage}
      PublicAccessBlockConfiguration:
        BlockPublicAcls: True
        BlockPublicPolicy: True
      VersioningConfiguration: 
        Status: "Enabled"

