Resources:
  S3UserProfilesBucket:
    Type: AWS::S3::Bucket
    Properties: 
      AccessControl: PublicRead
      BucketName: ${self:custom.s3UserProfilesBucketName}
      CorsConfiguration:
        CorsRules:
            - AllowedHeaders: 
                - "*"
              AllowedMethods: 
                - GET
                - PUT
              AllowedOrigins: 
                - "*"

  #Create policy to allow public access to avatar objects
  S3UserProfilesBucketPolicy: 
    Type: AWS::S3::BucketPolicy
    Properties: 
      Bucket: 
        Ref: "S3UserProfilesBucket"
      PolicyDocument: 
        Statement: 
          - 
            Action: 
              - "s3:GetObject"
            Effect: "Allow"
            Resource: 
              Fn::Join: 
                - ""
                - 
                  - "arn:aws:s3:::"
                  - 
                    Ref: "S3UserProfilesBucket"
                  - "/profile-avatar/*"
            Principal: "*"


